site_name:        'XDMarket'
site_author:      'MVSC'
site_description: 'XDMarket Project Documentation'
site_url:         'http://andyl.github.io/doctest'
site_favicon:     'img/favicon.gif'
theme:            'material'
copyright:        'Copyright &copy; 2017 Mountain View Smart Contracts'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/andyl/doctest'
markdown_extensions:
  - admonition
  - toc(permalink=true)
pages:
  - Home:             index.md
  - Usage Scenarios:  scenarios.md
  - Use Cases:   
    - Overview:            use_cases.md
    - All Roles:           cases/all_roles.md
    - Product Manager:     cases/product_manager.md
  - Software Objects: objects.md
  - Incentives:       incentive.md
  - Dapps:            dapp.md
  - IPFS:             ipfs.md
